[package]
name = "csv_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
fake = { version = "4.4.0", features = ["derive"] }
serde =  { version = "1.0.225", features = ["derive"] }
